# CosmoPrinters plugin, made by Levitate.

# Name of the printer item
item-name: "&3&l[!] &b&lPrinter &3&l[!]"

# Lore of the printer item
item-lore:
  - "&7Leave this in your inventory to earn passive income"
  - ""

# Amount of money earned from printer every x seconds
# Default is 10000, I do recommend changing this depending on how your economy is though.
printer-money: 10000

# Amount of money you need to pay to upgrade printer
# Default is 10000, I do recommend changing this depending on how your economy is though.
upgrade-price: 10000

# The multiplier of how much more money the player will earn per upgrade
# Default is 1.5
upgrade-earnings-increase: 1.5

# How much the upgrade price multiplies per upgrade
# Default is 3
upgrade-price-multiplier: 3

# Maximum amount of times the printer can be upgraded
# Default is 15
max-upgrades: 15

# Amount of time in seconds to get money from printer by default.
# Default is 3600 seconds = 1 hour.
printer-time: 3600

# Message received when the player is missing permissions
no-permission: "&4• &cYou don't have permission to use this command."

# Message received by the sender of a printer
sent-message: "&2• &aYou have sent a printer."

# Message received by the sender of a printer when there is an error while sending a printer.
error-sending: "&4• &cFailed to send a printer, make sure the target player exists."

# Message received by the person who was given the printer
received-message: "&2• &aYou have received a printer."

# Message received when running upgrade command but not holding a printer
not-holding-printer: "&4• &cYou must be holding a printer to use this command."

# Message received when trying to upgrade printer when it's already at maximum upgrades
already-max-upgrades: "&4• &cYou are already at maximum upgrades."

# Message received when player doesn't have enough money to upgrade printer.
not-enough-money: "&4• &cYou do not have enough money to upgrade this printer."

# Message received when upgrading printer.
printer-upgraded: "&2• &aYou have upgraded your printer to "
